/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CrossBridge__factory } from "./CrossBridge__factory";
export { ERC20__factory } from "./ERC20__factory";
